### ISSUE TITLE
Incorrect placement of script tags

### ISSUE THREAD

**Issue by mnichols08** [bloominstituteoftechnology/JavaScript-I#741]
The provided Index.html places the script tags in the head of the document instead of at the bottom of the body tag.

**Comment by moingshaikh** [comment]
Hi @mnichols08, I was just randomly searching for some .js issues to contribute to and found your this issue. 

As far as I know about script tags and their placement in an html document, the modern standard practice is to place script tag between <head></head> tags provided the <script> uses the "async" attribute which will help browser render html document while simultaneously parsing the script under the <script> tag.

Hence, in my view, "async" attribute should be added to the <script> tag without having to change its placement in the document; something similar to this:

<script src="objects.js" async></script>
  <script src="arrays.js" async></script>
  <script src="function-conversion.js" async></script>

**Comment by mnichols08** [comment]
Students will be doomed to failure on that without fixing the bug given to them off the bat. Go Lambda. I mean umm what is it now? Bloom. Yeah. Whatever i tried helping when I was there. Good luck
